#!/usr/bin/env sh
if [ ! $2 ]; then
	echo Usage: $0 user IP
	exit 1
fi
user=$1
IP=$2
cd ../..
rsync -zrpt --partial -e ssh hotrap $user@$IP:~/ --exclude='build'
rsync -zrpt --partial -e ssh viscnts-splay-rs $user@$IP:~/ --exclude='build'
rsync -zrpt --partial -e ssh kvexe $user@$IP:~/ --exclude='build'
ssh $user@$IP "./tests/helper/checkout-viscnts-splay-rs"
