#!/usr/bin/env bash
if [ ! $2 ]; then
	echo Usage: $0 user IP
	exit 1
fi
user=$1
IP=$2
cd ../..
rsync -zPrt -e ssh rocksdb $user@$IP:~/ --exclude='build'
rsync -zPrt -e ssh kvexe-secondary-cache $user@$IP:~/ --exclude='build'
ssh $user@$IP "mkdir -p opt/cachelib"
rsync -zPrlt -e ssh $CACHELIB_HOME/* $user@$IP:~/opt/cachelib/ --exclude='tests' --exclude='test_configs' --exclude='bin'
ssh $user@$IP "find opt/cachelib -name \"lib*.so*\" | xargs -i patchelf --set-rpath \"\$HOME/opt/cachelib/lib\" {}"
ssh $user@$IP "echo \"
export CACHELIB_HOME=\\\$HOME/opt/cachelib
export CPLUS_INCLUDE_PATH=\\\$CACHELIB_HOME/include:\\\$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=\\\$CACHELIB_HOME/lib:\\\$LIBRARY_PATH
export LD_LIBRARY_PATH=\\\$CACHELIB_HOME/lib:\\\$LD_LIBRARY_PATH
\" >> .profile"
ssh $user@$IP "source .profile && ./tests/helper/checkout-secondary-cache"
