#!/usr/bin/env sh
if [ ! $3 ]; then
	echo Usage: $0 user IP version
	exit 1
fi
user=$1
IP=$2
version=$3
cd ../..
rsync -zrpt --partial -e ssh hotrap $user@$IP:~/ --exclude='build'
rsync -zrpt --partial -e ssh RALT $user@$IP:~/ --exclude='build'
rsync -zrpt --partial -e ssh kvexe $user@$IP:~/ --exclude='build'
ssh $user@$IP "./tests/helper/checkout-$version"