#!/usr/bin/env sh
set -e

cd $(dirname $0)
. ./common.sh
cd ..

cd ../hotrap
git checkout main
build_rocksdb

cd ../viscnts-splay-rs
git checkout main
build_viscnts_splay_rs

cd ../hotrap
build_db_bench_viscnts_splay_rs

cd ../kvexe
git checkout main
build_kvexe_viscnts_splay_rs
