#!/usr/bin/env bash
set -e

cd $(dirname $0)
source common.sh
cd ..

cd ../hotrap
git checkout no-promote-by-compaction
build_rocksdb

cd ../RALT
build_ralt

cd ../kvexe
git checkout main
build_kvexe_ralt
