#!/usr/bin/env bash
cd $(dirname $0)
source common.sh
cd ..

cd ../hotrap
git checkout flush-stable-hot
build_rocksdb

cd ../viscnts-splay-rs
git checkout single-tier-stable
build_viscnts_splay_rs

cd ../kvexe
git checkout single-tier
build_kvexe

