#!/usr/bin/env bash
set -e

cd $(dirname $0)
source common.sh
cd ../..

cd prismdb
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_DIO=ON
make -j$(nproc)
cd ../..

cd kvexe-prismdb
rm -rf build
build_kvexe_prismdb
