#!/usr/bin/env bash
set -e

cd $(dirname $0)
source common.sh
cd ../..

cd prismdb
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
cd ../..

cd kvexe-prismdb
build_kvexe_prismdb
