#!/usr/bin/env bash
if [ ! $1 ]; then
	echo Usage: $0 workload-name version-name
	exit 1
fi
set -e
cd $(dirname $0)
./checkout-$2
cd ../workloads
bash $1-$2.sh
cd ../../data
mkdir -p $1
mv $1-$2/ $1/$2
