#!/usr/bin/env bash
if [ ! $1 ]; then
	echo Usage: $0 IP
	exit 1
fi
cd ../..
rsync -zPrt -e ssh rocksdb root@$1:~/ --exclude='build'
rsync -zPrt -e ssh kvexe-secondary-cache root@$1:~/ --exclude='build'
rsync -zPrlt -e ssh $CACHELIB_HOME root@$1:/opt/ --exclude='cachelib/tests' --exclude='cachelib/test_configs' --exclude='cachelib/bin'
ssh root@$1 "echo 'export CACHELIB_HOME=/opt/cachelib' >> .profile"
# libthrift-core.so.1.0.0 not found even with correct RUNPATH in "readelf -d rocksdb-kvexe". Weird
ssh root@$1 "echo 'export LD_LIBRARY_PATH=/opt/cachelib/lib:$LD_LIBRARY_PATH' >> .profile"
ssh root@$1 "source .profile && ./tests/helper/checkout-secondary-cache"
