all: maxmemory ops latency
.PHONY: all

maxmemory: maxmemory.cpp
	g++ -O3 maxmemory.cpp -o maxmemory --std=c++20

ops: ops.cpp
	g++ -O3 ops.cpp -o ops --std=c++20

latency: latency.cpp
	g++ -O3 latency.cpp -o latency --std=c++20