#!/usr/bin/env sh
set -e
count_total=$(tail -n1 seek-count-time | cut -sd' ' -f2)
micros_total=$(tail -n1 seek-count-time | cut -sd' ' -f3)
count_90p=$((count_total * 9 / 10))
res=$(awk "{
	if (NR > 1 && \$2 >= $count_90p) {
		print \$2, \$3;
		exit 0
	}
}" seek-count-time)
count_90p=$(echo $res | cut -sd" " -f1)
micros_90p=$(echo $res | cut -sd" " -f2)
num_op=$((count_total - count_90p))
micros=$((micros_total - micros_90p))
echo "$micros / 1000000 / $num_op" | bc -l
