#!/usr/bin/env sh
set -e
timestamp_100p=$(hjson-cli -j < info.json | jq -er ".\"run-end-timestamp(ns)\"")
num_total_op=$(tail -n1 progress | cut -sd' ' -f2)
run_start_timestamp=$(hjson-cli -j < info.json | jq -er ".\"run-start-timestamp(ns)\"")
run_start_progress=$(awk "
	BEGIN {
		res = 0
	}
	{
		if (NR > 1 && \$1 >= $run_start_timestamp) {
			res = \$2;
			exit 0
		}
	}
	END {
		print res
	}
" progress)
num_run_op=$((num_total_op - run_start_progress))
progress_90p=$((run_start_progress + num_run_op * 9 / 10))
res=$(awk "{
	if (NR > 1 && \$2 >= $progress_90p) {
		print \$1, \$2;
		exit 0
	}
}" progress)
timestamp_90p=$(echo $res | cut -sd" " -f1)
progress_90p=$(echo $res | cut -sd" " -f2)
num_op=$((num_total_op - progress_90p))
echo "$num_op / (($timestamp_100p - $timestamp_90p) / 1000000000)" | bc -l
